version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
    timezone: US/Central
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
    timezone: US/Central
